<?php

namespace Database\Seeders;

use App\Models\Job;
use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach(range(6, 50) as $item) {
            Job::create([
                'company_id' => 1,
                'job_no' => rand(1000, 9999),
                'job_title' => 'information technology job recruitment_No' . $item,
                'job_detail' => "Under the web project manager, we'll assist in generating proposals, coordinate production teams such as web designers and front-end engineers, and perform web directing. In addition, we will analyze the effects and recommend improvements to the generated web content.

                Specifically,

                1) Support production proposals and generate budgets and working hours for proposals generated by web project manager.
                2) Schedule management, work hours and process management, membership management, quality control and issue management for content production web.
                3) Do production instructions, specific production instructions to relevant departments inside and outside the company
                4) Continuously measure web content performance and make recommendations for improvement",
                'job_status' => 1,
                'location_detail' => 'Da Nang',
                'english_level' => 2,
                'experienced_count' => 2,
                'age_min' => 18,
                'age_max' => 40,
                'position_name' => 'Da Nang',
                'salary_type' => 1,
                'salary_min' => 10,
                'salary_max' => 30,
                'salary_detail' => '10 triệu VND ~ 30 triệu VND',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
